#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : AckChecker.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Apr 29 14:08:09 +0300 2020
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: AckChecker.sh [-help]
# usage: AckChecker.sh [-lib_map_path]
# usage: AckChecker.sh [-noclean_files]
# usage: AckChecker.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'AckChecker.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "AckChecker.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/AckChecker/ipshared/d6cf/AckCheckerConcept.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_0_0/sim/AckChecker_AckCheckerConcept_0_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_0_1/sim/AckChecker_AckCheckerConcept_0_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_0_2/sim/AckChecker_AckCheckerConcept_0_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_0_3/sim/AckChecker_AckCheckerConcept_0_3.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_0_4/sim/AckChecker_AckCheckerConcept_0_4.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_1_0/sim/AckChecker_AckCheckerConcept_1_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_2_0/sim/AckChecker_AckCheckerConcept_2_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_3_0/sim/AckChecker_AckCheckerConcept_3_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_4_1/sim/AckChecker_AckCheckerConcept_4_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_5_1/sim/AckChecker_AckCheckerConcept_5_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_6_1/sim/AckChecker_AckCheckerConcept_6_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_7_1/sim/AckChecker_AckCheckerConcept_7_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_4_2/sim/AckChecker_AckCheckerConcept_4_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_5_2/sim/AckChecker_AckCheckerConcept_5_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_6_2/sim/AckChecker_AckCheckerConcept_6_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_7_2/sim/AckChecker_AckCheckerConcept_7_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_12_0/sim/AckChecker_AckCheckerConcept_12_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_13_0/sim/AckChecker_AckCheckerConcept_13_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_14_0/sim/AckChecker_AckCheckerConcept_14_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_15_0/sim/AckChecker_AckCheckerConcept_15_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_12_1/sim/AckChecker_AckCheckerConcept_12_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_13_1/sim/AckChecker_AckCheckerConcept_13_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_14_1/sim/AckChecker_AckCheckerConcept_14_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_15_1/sim/AckChecker_AckCheckerConcept_15_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_12_2/sim/AckChecker_AckCheckerConcept_12_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_13_2/sim/AckChecker_AckCheckerConcept_13_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_14_2/sim/AckChecker_AckCheckerConcept_14_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_15_2/sim/AckChecker_AckCheckerConcept_15_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_12_3/sim/AckChecker_AckCheckerConcept_12_3.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_13_3/sim/AckChecker_AckCheckerConcept_13_3.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_14_3/sim/AckChecker_AckCheckerConcept_14_3.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_AckCheckerConcept_15_3/sim/AckChecker_AckCheckerConcept_15_3.vhd" \
    "$ref_dir/../../../bd/AckChecker/ipshared/dbb3/BusBlock16OUT.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16OUT_0_0/sim/AckChecker_BusBlock16OUT_0_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16OUT_0_1/sim/AckChecker_BusBlock16OUT_0_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16OUT_0_2/sim/AckChecker_BusBlock16OUT_0_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16OUT_1_0/sim/AckChecker_BusBlock16OUT_1_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ipshared/2edf/BusBlock16IN.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16IN_0_0/sim/AckChecker_BusBlock16IN_0_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16IN_0_1/sim/AckChecker_BusBlock16IN_0_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16IN_0_2/sim/AckChecker_BusBlock16IN_0_2.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16IN_2_0/sim/AckChecker_BusBlock16IN_2_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16IN_1_0/sim/AckChecker_BusBlock16IN_1_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16IN_4_0/sim/AckChecker_BusBlock16IN_4_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16IN_4_1/sim/AckChecker_BusBlock16IN_4_1.vhd" \
    "$ref_dir/../../../bd/AckChecker/ip/AckChecker_BusBlock16IN_6_0/sim/AckChecker_BusBlock16IN_6_0.vhd" \
    "$ref_dir/../../../bd/AckChecker/sim/AckChecker.vhd" \
  2>&1 | tee -a vhdlan.log



}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.AckChecker -o AckChecker_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./AckChecker_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./AckChecker.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key AckChecker_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc AckChecker_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./AckChecker.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: AckChecker.sh [-help]\n\
Usage: AckChecker.sh [-lib_map_path]\n\
Usage: AckChecker.sh [-reset_run]\n\
Usage: AckChecker.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
