# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Inverter_3lvl/Inverter_3lvl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl || ORIG_REF_NAME==Inverter_3lvl} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_P0N_3lvl_0_0/Inverter_3lvl_P0N_3lvl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_0 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_0} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_P0N_3lvl_1_0/Inverter_3lvl_P0N_3lvl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_1_0 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_1_0} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_P0N_3lvl_1_1/Inverter_3lvl_P0N_3lvl_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_1_1 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_1_1} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_P0N_3lvl_0_1/Inverter_3lvl_P0N_3lvl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_1 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_1} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_P0N_3lvl_0_2/Inverter_3lvl_P0N_3lvl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_2 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_2} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_P0N_3lvl_0_3/Inverter_3lvl_P0N_3lvl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_3 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_3} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_P0N_3lvl_0_4/Inverter_3lvl_P0N_3lvl_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_4 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_4} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_P0N_3lvl_0_5/Inverter_3lvl_P0N_3lvl_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_5 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_5} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_BUS_16IN_0_0/Inverter_3lvl_BUS_16IN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16IN_0_0 || ORIG_REF_NAME==Inverter_3lvl_BUS_16IN_0_0} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_BUS_16IN_1_0/Inverter_3lvl_BUS_16IN_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16IN_1_0 || ORIG_REF_NAME==Inverter_3lvl_BUS_16IN_1_0} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_BUS_16OUT_0_0/Inverter_3lvl_BUS_16OUT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16OUT_0_0 || ORIG_REF_NAME==Inverter_3lvl_BUS_16OUT_0_0} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_BUS_16OUT_0_1/Inverter_3lvl_BUS_16OUT_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16OUT_0_1 || ORIG_REF_NAME==Inverter_3lvl_BUS_16OUT_0_1} -quiet] -quiet

# IP: bd/Inverter_3lvl/ip/Inverter_3lvl_BUS_16OUT_1_0/Inverter_3lvl_BUS_16OUT_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16OUT_1_0 || ORIG_REF_NAME==Inverter_3lvl_BUS_16OUT_1_0} -quiet] -quiet

# XDC: bd/Inverter_3lvl/Inverter_3lvl_ooc.xdc
