# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0.xci
# IP: The module: 'UPzynq20_test_design_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UPzynq20_test_design_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UPzynq20_test_design_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UPzynq20_test_design_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0.xci
# IP: The module: 'UPzynq20_test_design_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UPzynq20_test_design_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UPzynq20_test_design_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UPzynq20_test_design_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
