# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/UPzynq20_test_design/UPzynq20_test_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design || ORIG_REF_NAME==UPzynq20_test_design} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_xbar_0/UPzynq20_test_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_xbar_0 || ORIG_REF_NAME==UPzynq20_test_design_xbar_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_ps7_0_axi_periph_0/UPzynq20_test_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==UPzynq20_test_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_processing_system7_0_0_1/UPzynq20_test_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_processing_system7_0_0 || ORIG_REF_NAME==UPzynq20_test_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_0_0_1/UPzynq20_test_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_0_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_2_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_2_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_3_0/UPzynq20_test_design_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_3_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_3_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_rst_ps7_0_50M_0_1/UPzynq20_test_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==UPzynq20_test_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_IP_AXI_LEDS_0_0/UPzynq20_test_design_IP_AXI_LEDS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_IP_AXI_LEDS_0_0 || ORIG_REF_NAME==UPzynq20_test_design_IP_AXI_LEDS_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_IP_AXI_Encoder_0_0/UPzynq20_test_design_IP_AXI_Encoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_IP_AXI_Encoder_0_0 || ORIG_REF_NAME==UPzynq20_test_design_IP_AXI_Encoder_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_IP_AXI_PWM_0_0/UPzynq20_test_design_IP_AXI_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_IP_AXI_PWM_0_0 || ORIG_REF_NAME==UPzynq20_test_design_IP_AXI_PWM_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_IP_AXI_OpticalBus_0_0/UPzynq20_test_design_IP_AXI_OpticalBus_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_IP_AXI_OpticalBus_0_0 || ORIG_REF_NAME==UPzynq20_test_design_IP_AXI_OpticalBus_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/UPzynq20_test_design_AckChecker_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_AckChecker_wrapper_0_0 || ORIG_REF_NAME==UPzynq20_test_design_AckChecker_wrapper_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_0_0/AckChecker_AckCheckerConcept_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_0_0 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_0_1/AckChecker_AckCheckerConcept_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_0_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_0_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_0_2/AckChecker_AckCheckerConcept_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_0_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_0_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_0_3/AckChecker_AckCheckerConcept_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_0_3 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_0_3} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_0_4/AckChecker_AckCheckerConcept_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_0_4 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_0_4} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_1_0/AckChecker_AckCheckerConcept_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_1_0 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_1_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_2_0/AckChecker_AckCheckerConcept_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_2_0 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_2_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_3_0/AckChecker_AckCheckerConcept_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_3_0 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_3_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_4_1/AckChecker_AckCheckerConcept_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_4_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_4_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_5_1/AckChecker_AckCheckerConcept_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_5_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_5_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_6_1/AckChecker_AckCheckerConcept_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_6_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_6_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_7_1/AckChecker_AckCheckerConcept_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_7_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_7_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_4_2/AckChecker_AckCheckerConcept_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_4_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_4_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_5_2/AckChecker_AckCheckerConcept_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_5_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_5_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_6_2/AckChecker_AckCheckerConcept_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_6_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_6_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_7_2/AckChecker_AckCheckerConcept_7_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_7_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_7_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_12_0/AckChecker_AckCheckerConcept_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_12_0 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_12_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_13_0/AckChecker_AckCheckerConcept_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_13_0 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_13_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_14_0/AckChecker_AckCheckerConcept_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_14_0 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_14_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_15_0/AckChecker_AckCheckerConcept_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_15_0 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_15_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_12_1/AckChecker_AckCheckerConcept_12_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_12_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_12_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_13_1/AckChecker_AckCheckerConcept_13_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_13_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_13_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_14_1/AckChecker_AckCheckerConcept_14_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_14_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_14_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_15_1/AckChecker_AckCheckerConcept_15_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_15_1 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_15_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_12_2/AckChecker_AckCheckerConcept_12_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_12_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_12_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_13_2/AckChecker_AckCheckerConcept_13_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_13_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_13_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_14_2/AckChecker_AckCheckerConcept_14_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_14_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_14_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_15_2/AckChecker_AckCheckerConcept_15_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_15_2 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_15_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_12_3/AckChecker_AckCheckerConcept_12_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_12_3 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_12_3} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_13_3/AckChecker_AckCheckerConcept_13_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_13_3 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_13_3} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_14_3/AckChecker_AckCheckerConcept_14_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_14_3 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_14_3} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_AckCheckerConcept_15_3/AckChecker_AckCheckerConcept_15_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_AckCheckerConcept_15_3 || ORIG_REF_NAME==AckChecker_AckCheckerConcept_15_3} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16OUT_0_0/AckChecker_BusBlock16OUT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16OUT_0_0 || ORIG_REF_NAME==AckChecker_BusBlock16OUT_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16OUT_0_1/AckChecker_BusBlock16OUT_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16OUT_0_1 || ORIG_REF_NAME==AckChecker_BusBlock16OUT_0_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16OUT_0_2/AckChecker_BusBlock16OUT_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16OUT_0_2 || ORIG_REF_NAME==AckChecker_BusBlock16OUT_0_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16OUT_1_0/AckChecker_BusBlock16OUT_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16OUT_1_0 || ORIG_REF_NAME==AckChecker_BusBlock16OUT_1_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16IN_0_0/AckChecker_BusBlock16IN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16IN_0_0 || ORIG_REF_NAME==AckChecker_BusBlock16IN_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16IN_0_1/AckChecker_BusBlock16IN_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16IN_0_1 || ORIG_REF_NAME==AckChecker_BusBlock16IN_0_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16IN_0_2/AckChecker_BusBlock16IN_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16IN_0_2 || ORIG_REF_NAME==AckChecker_BusBlock16IN_0_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16IN_2_0/AckChecker_BusBlock16IN_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16IN_2_0 || ORIG_REF_NAME==AckChecker_BusBlock16IN_2_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16IN_1_0/AckChecker_BusBlock16IN_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16IN_1_0 || ORIG_REF_NAME==AckChecker_BusBlock16IN_1_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16IN_4_0/AckChecker_BusBlock16IN_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16IN_4_0 || ORIG_REF_NAME==AckChecker_BusBlock16IN_4_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16IN_4_1/AckChecker_BusBlock16IN_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16IN_4_1 || ORIG_REF_NAME==AckChecker_BusBlock16IN_4_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/ip/AckChecker_BusBlock16IN_6_0/AckChecker_BusBlock16IN_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AckChecker_BusBlock16IN_6_0 || ORIG_REF_NAME==AckChecker_BusBlock16IN_6_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_IP_AXI_INVERTER_0_0/UPzynq20_test_design_IP_AXI_INVERTER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_IP_AXI_INVERTER_0_0 || ORIG_REF_NAME==UPzynq20_test_design_IP_AXI_INVERTER_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_Inverter_3lvl_wrapper_0_1 || ORIG_REF_NAME==UPzynq20_test_design_Inverter_3lvl_wrapper_0_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_P0N_3lvl_0_5/Inverter_3lvl_P0N_3lvl_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_5 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_5} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_P0N_3lvl_0_4/Inverter_3lvl_P0N_3lvl_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_4 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_4} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_P0N_3lvl_0_3/Inverter_3lvl_P0N_3lvl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_3 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_3} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_P0N_3lvl_0_2/Inverter_3lvl_P0N_3lvl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_2 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_2} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_P0N_3lvl_0_1/Inverter_3lvl_P0N_3lvl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_1 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_P0N_3lvl_1_1/Inverter_3lvl_P0N_3lvl_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_1_1 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_1_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_P0N_3lvl_1_0/Inverter_3lvl_P0N_3lvl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_1_0 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_1_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_P0N_3lvl_0_0/Inverter_3lvl_P0N_3lvl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_P0N_3lvl_0_0 || ORIG_REF_NAME==Inverter_3lvl_P0N_3lvl_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_BUS_16OUT_1_0/Inverter_3lvl_BUS_16OUT_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16OUT_1_0 || ORIG_REF_NAME==Inverter_3lvl_BUS_16OUT_1_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_BUS_16OUT_0_1/Inverter_3lvl_BUS_16OUT_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16OUT_0_1 || ORIG_REF_NAME==Inverter_3lvl_BUS_16OUT_0_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_BUS_16OUT_0_0/Inverter_3lvl_BUS_16OUT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16OUT_0_0 || ORIG_REF_NAME==Inverter_3lvl_BUS_16OUT_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_BUS_16IN_1_0/Inverter_3lvl_BUS_16IN_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16IN_1_0 || ORIG_REF_NAME==Inverter_3lvl_BUS_16IN_1_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/ip/Inverter_3lvl_BUS_16IN_0_0/Inverter_3lvl_BUS_16IN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inverter_3lvl_BUS_16IN_0_0 || ORIG_REF_NAME==Inverter_3lvl_BUS_16IN_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_IP_AXI_ADC_0_1/UPzynq20_test_design_IP_AXI_ADC_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_IP_AXI_ADC_0_1 || ORIG_REF_NAME==UPzynq20_test_design_IP_AXI_ADC_0_1} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_xlconcat_0_0/UPzynq20_test_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_xlconcat_0_0 || ORIG_REF_NAME==UPzynq20_test_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/UPzynq20_test_design/ip/UPzynq20_test_design_auto_pc_0/UPzynq20_test_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_auto_pc_0 || ORIG_REF_NAME==UPzynq20_test_design_auto_pc_0} -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_processing_system7_0_0_1/UPzynq20_test_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_processing_system7_0_0 || ORIG_REF_NAME==UPzynq20_test_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_0_0_1/UPzynq20_test_design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_0_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_0_0_1/UPzynq20_test_design_axi_gpio_0_0_ooc.xdc

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_0_0_1/UPzynq20_test_design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_0_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_2_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0_ooc.xdc

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_2_0_1/UPzynq20_test_design_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_2_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_3_0/UPzynq20_test_design_axi_gpio_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_3_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_3_0/UPzynq20_test_design_axi_gpio_3_0_ooc.xdc

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_axi_gpio_3_0/UPzynq20_test_design_axi_gpio_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_axi_gpio_3_0 || ORIG_REF_NAME==UPzynq20_test_design_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_rst_ps7_0_50M_0_1/UPzynq20_test_design_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==UPzynq20_test_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_rst_ps7_0_50M_0_1/UPzynq20_test_design_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==UPzynq20_test_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==UPzynq20_test_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_AckChecker_wrapper_0_0/AckChecker_ooc.xdc

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_Inverter_3lvl_wrapper_0_1/Inverter_3lvl_ooc.xdc

# XDC: bd/UPzynq20_test_design/ip/UPzynq20_test_design_auto_pc_0/UPzynq20_test_design_auto_pc_0_ooc.xdc

# XDC: bd/UPzynq20_test_design/UPzynq20_test_design_ooc.xdc
