# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_processing_system7_0_0_1/UPzynq20_test_design_processing_system7_0_0.xci
# IP: The module: 'UPzynq20_test_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_processing_system7_0_0_1/UPzynq20_test_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UPzynq20_test_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_processing_system7_0_0_1/UPzynq20_test_design_processing_system7_0_0.xci
# IP: The module: 'UPzynq20_test_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/XilinxProjects/UPzynq20_test/UPzynq20_test.srcs/sources_1/bd/UPzynq20_test_design/ip/UPzynq20_test_design_processing_system7_0_0_1/UPzynq20_test_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UPzynq20_test_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
