
#светодиод на морде
set_property DRIVE 12 [get_ports LEDS_0]
set_property PACKAGE_PIN U6 [get_ports LEDS_0]
set_property IOSTANDARD LVCMOS33 [get_ports LEDS_0]

#светодиод на устройстве
set_property DRIVE 12 [get_ports LEDS_1]
set_property PACKAGE_PIN U5 [get_ports LEDS_1]
set_property IOSTANDARD LVCMOS33 [get_ports LEDS_1]

#режим работы LoadMode (A26)
set_property DRIVE 12 [get_ports LoadMode]
set_property PACKAGE_PIN AB21 [get_ports LoadMode]
set_property IOSTANDARD LVCMOS33 [get_ports LoadMode]

#режим работы светодиодной индикации DivClk (A25)
set_property DRIVE 12 [get_ports DivClk_0]
set_property PACKAGE_PIN V19 [get_ports DivClk_0]
set_property IOSTANDARD LVCMOS33 [get_ports DivClk_0]

#режим работы светодиодной индикации AsyncLine (B25)
set_property DRIVE 12 [get_ports AsyncLine_0]
set_property PACKAGE_PIN Y21 [get_ports AsyncLine_0]
set_property IOSTANDARD LVCMOS33 [get_ports AsyncLine_0]

#Глобальная ошибка Er0 (C8)
set_property PACKAGE_PIN J15 [get_ports Er0]
set_property IOSTANDARD LVCMOS33 [get_ports Er0]



#SerialBus

set_property PACKAGE_PIN W16 [get_ports Data_In_1]
set_property IOSTANDARD LVCMOS33 [get_ports Data_In_1]

set_property DRIVE 12 [get_ports OUT_put_0]
set_property PACKAGE_PIN L16 [get_ports OUT_put_0]
set_property IOSTANDARD LVCMOS33 [get_ports OUT_put_0]

set_property DRIVE 12 [get_ports OUT_put_Dif_0]
set_property PACKAGE_PIN R16 [get_ports OUT_put_Dif_0]
set_property IOSTANDARD LVCMOS33 [get_ports OUT_put_Dif_0]

set_property DRIVE 12 [get_ports OUT_put_1]
set_property PACKAGE_PIN N19 [get_ports OUT_put_1]
set_property IOSTANDARD LVCMOS33 [get_ports OUT_put_1]

set_property DRIVE 12 [get_ports OUT_put_Dif_1]
set_property PACKAGE_PIN M19 [get_ports OUT_put_Dif_1]
set_property IOSTANDARD LVCMOS33 [get_ports OUT_put_Dif_1]



#ParallelBus

set_property DRIVE 12 [get_ports EnableBus_0]
set_property PACKAGE_PIN AA21 [get_ports EnableBus_0]
set_property IOSTANDARD LVCMOS33 [get_ports EnableBus_0]

set_property DRIVE 12 [get_ports ClkBus_0]
set_property PACKAGE_PIN AA19 [get_ports ClkBus_0]
set_property IOSTANDARD LVCMOS33 [get_ports ClkBus_0]

set_property PACKAGE_PIN T16 [get_ports AcknowledgeBus_0]
set_property IOSTANDARD LVCMOS33 [get_ports AcknowledgeBus_0]

set_property PACKAGE_PIN V22 [get_ports {DataBus_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[0]}]
set_property PACKAGE_PIN P21 [get_ports {DataBus_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[1]}]
set_property PACKAGE_PIN N15 [get_ports {DataBus_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[2]}]
set_property PACKAGE_PIN W22 [get_ports {DataBus_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[3]}]
set_property PACKAGE_PIN P15 [get_ports {DataBus_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[4]}]
set_property PACKAGE_PIN R15 [get_ports {DataBus_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[5]}]
set_property PACKAGE_PIN U20 [get_ports {DataBus_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[6]}]
set_property PACKAGE_PIN T19 [get_ports {DataBus_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[7]}]
set_property PACKAGE_PIN T17 [get_ports {DataBus_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[8]}]
set_property PACKAGE_PIN P16 [get_ports {DataBus_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[9]}]
set_property PACKAGE_PIN AA22 [get_ports {DataBus_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[10]}]
set_property PACKAGE_PIN T22 [get_ports {DataBus_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[11]}]
set_property PACKAGE_PIN U22 [get_ports {DataBus_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[12]}]
set_property PACKAGE_PIN AB22 [get_ports {DataBus_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[13]}]
set_property PACKAGE_PIN W20 [get_ports {DataBus_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[14]}]
set_property PACKAGE_PIN W21 [get_ports {DataBus_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataBus_0[15]}]


set_property PACKAGE_PIN V20 [get_ports {gpio_rtl_0_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[0]}]
set_property PACKAGE_PIN R7 [get_ports {gpio_rtl_0_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[1]}]
set_property PACKAGE_PIN P18 [get_ports {gpio_rtl_0_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[2]}]
set_property PACKAGE_PIN M16 [get_ports {gpio_rtl_0_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[3]}]
set_property PACKAGE_PIN N18 [get_ports {gpio_rtl_0_tri_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[4]}]
set_property PACKAGE_PIN N20 [get_ports {gpio_rtl_0_tri_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[5]}]
set_property PACKAGE_PIN P17 [get_ports {gpio_rtl_0_tri_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[6]}]
set_property PACKAGE_PIN M17 [get_ports {gpio_rtl_0_tri_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[7]}]
set_property PACKAGE_PIN R20 [get_ports {gpio_rtl_0_tri_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[8]}]
set_property PACKAGE_PIN U15 [get_ports {gpio_rtl_0_tri_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[9]}]
set_property PACKAGE_PIN N17 [get_ports {gpio_rtl_0_tri_i[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[10]}]
set_property PACKAGE_PIN T18 [get_ports {gpio_rtl_0_tri_i[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[11]}]
set_property PACKAGE_PIN P22 [get_ports {gpio_rtl_0_tri_i[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[12]}]
set_property PACKAGE_PIN J16 [get_ports {gpio_rtl_0_tri_i[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[13]}]
set_property PACKAGE_PIN R21 [get_ports {gpio_rtl_0_tri_i[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[14]}]
set_property PACKAGE_PIN P20 [get_ports {gpio_rtl_0_tri_i[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_i[15]}]

set_property PACKAGE_PIN K16 [get_ports {gpio_rtl_1_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[0]}]
set_property PACKAGE_PIN R19 [get_ports {gpio_rtl_1_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[1]}]
set_property PACKAGE_PIN R18 [get_ports {gpio_rtl_1_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[2]}]
set_property PACKAGE_PIN T21 [get_ports {gpio_rtl_1_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[3]}]
set_property PACKAGE_PIN L22 [get_ports {gpio_rtl_1_tri_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[4]}]
set_property PACKAGE_PIN M22 [get_ports {gpio_rtl_1_tri_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[5]}]
set_property PACKAGE_PIN U21 [get_ports {gpio_rtl_1_tri_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[6]}]
set_property PACKAGE_PIN L21 [get_ports {gpio_rtl_1_tri_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[7]}]
set_property PACKAGE_PIN AB14 [get_ports {gpio_rtl_1_tri_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[8]}]
set_property PACKAGE_PIN V13 [get_ports {gpio_rtl_1_tri_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[9]}]
set_property PACKAGE_PIN N22 [get_ports {gpio_rtl_1_tri_i[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[10]}]
set_property PACKAGE_PIN V18 [get_ports {gpio_rtl_1_tri_i[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[11]}]
set_property PACKAGE_PIN Y20 [get_ports {gpio_rtl_1_tri_i[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[12]}]
set_property PACKAGE_PIN AB19 [get_ports {gpio_rtl_1_tri_i[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[13]}]
set_property PACKAGE_PIN Y19 [get_ports {gpio_rtl_1_tri_i[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[14]}]
#set_property PACKAGE_PIN Y19 [get_ports {gpio_rtl_1_tri_i[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[15]}]


set_property PACKAGE_PIN K21 [get_ports {ChGroup0_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[0]}]
set_property PACKAGE_PIN K19 [get_ports {ChGroup0_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[1]}]
set_property PACKAGE_PIN M21 [get_ports {ChGroup0_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[2]}]
set_property PACKAGE_PIN J22 [get_ports {ChGroup0_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[3]}]
set_property PACKAGE_PIN J21 [get_ports {ChGroup0_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[4]}]
set_property PACKAGE_PIN J18 [get_ports {ChGroup0_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[5]}]
set_property PACKAGE_PIN K18 [get_ports {ChGroup0_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[6]}]
set_property PACKAGE_PIN J20 [get_ports {ChGroup0_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[7]}]
set_property PACKAGE_PIN J17 [get_ports {ChGroup0_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[8]}]
set_property PACKAGE_PIN H15 [get_ports {ChGroup0_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[9]}]
set_property PACKAGE_PIN L17 [get_ports {ChGroup0_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[10]}]
set_property PACKAGE_PIN L19 [get_ports {ChGroup0_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[11]}]
set_property PACKAGE_PIN K15 [get_ports {ChGroup0_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[12]}]
set_property PACKAGE_PIN L18 [get_ports {ChGroup0_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[13]}]
set_property PACKAGE_PIN M15 [get_ports {ChGroup0_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[14]}]
set_property PACKAGE_PIN M20 [get_ports {ChGroup0_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ChGroup0_0[15]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_5_tri_i[0]}]
#set_property PACKAGE_PIN V17 [get_ports {gpio_rtl_5_tri_i[9]}]
set_property PACKAGE_PIN U17 [get_ports {gpio_rtl_5_tri_i[8]}]
set_property PACKAGE_PIN Y16 [get_ports {gpio_rtl_5_tri_i[7]}]
set_property PACKAGE_PIN W18 [get_ports {gpio_rtl_5_tri_i[6]}]
set_property PACKAGE_PIN AA18 [get_ports {gpio_rtl_5_tri_i[5]}]
set_property PACKAGE_PIN W17 [get_ports {gpio_rtl_5_tri_i[4]}]
set_property PACKAGE_PIN AB20 [get_ports {gpio_rtl_5_tri_i[3]}]
set_property PACKAGE_PIN U16 [get_ports {gpio_rtl_5_tri_i[2]}]
set_property PACKAGE_PIN Y18 [get_ports {gpio_rtl_5_tri_i[1]}]
set_property PACKAGE_PIN V17 [get_ports {gpio_rtl_5_tri_i[0]}]


set_property KEEPER true [get_ports {DataBus_0[14]}]
set_property KEEPER true [get_ports {DataBus_0[13]}]
set_property KEEPER true [get_ports {DataBus_0[12]}]
set_property KEEPER true [get_ports {DataBus_0[11]}]
set_property KEEPER true [get_ports {DataBus_0[10]}]
set_property KEEPER true [get_ports {DataBus_0[9]}]
set_property KEEPER true [get_ports {DataBus_0[8]}]
set_property KEEPER true [get_ports {DataBus_0[7]}]
set_property KEEPER true [get_ports {DataBus_0[6]}]
set_property KEEPER true [get_ports {DataBus_0[5]}]
set_property KEEPER true [get_ports {DataBus_0[4]}]
set_property KEEPER true [get_ports {DataBus_0[3]}]
set_property KEEPER true [get_ports {DataBus_0[2]}]
set_property KEEPER true [get_ports {DataBus_0[1]}]
set_property KEEPER true [get_ports {DataBus_0[0]}]
set_property KEEPER true [get_ports {DataBus_0[15]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[15]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[14]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[13]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[12]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[11]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[10]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[9]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[8]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[7]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[6]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[5]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[4]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[3]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[2]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[1]}]
set_property SLEW SLOW [get_ports {ChGroup0_0[0]}]
set_property SLEW SLOW [get_ports {DataBus_0[15]}]
set_property SLEW SLOW [get_ports {DataBus_0[14]}]
set_property SLEW SLOW [get_ports {DataBus_0[13]}]
set_property SLEW SLOW [get_ports {DataBus_0[12]}]
set_property SLEW SLOW [get_ports {DataBus_0[11]}]
set_property SLEW SLOW [get_ports {DataBus_0[10]}]
set_property SLEW SLOW [get_ports {DataBus_0[9]}]
set_property SLEW SLOW [get_ports {DataBus_0[8]}]
set_property SLEW SLOW [get_ports {DataBus_0[7]}]
set_property SLEW SLOW [get_ports {DataBus_0[6]}]
set_property SLEW SLOW [get_ports {DataBus_0[5]}]
set_property SLEW SLOW [get_ports {DataBus_0[4]}]
set_property SLEW SLOW [get_ports {DataBus_0[3]}]
set_property SLEW SLOW [get_ports {DataBus_0[2]}]
set_property SLEW SLOW [get_ports {DataBus_0[1]}]
set_property SLEW SLOW [get_ports {DataBus_0[0]}]


